language: python
python:
    - "3.6"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
before_install:
    - pip install pipenv
    - pipenv install --dev --skip-lock
script:
    - pipenv run pycodestyle specsavers/
    - pipenv run pycodestyle tests/
    - pipenv run python -m unittest discover tests/
