language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
before_install:
    - pip install poetry
install:
    - poetry install
script:
    - poetry run pycodestyle specsavers/
    - poetry run pycodestyle tests/
    - poetry run pytest tests/
