language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
before_install:
    - pip install pipenv
    - pipenv install --dev --skip-lock
script:
    - pipenv run pycodestyle specsavers/
    - pipenv run pycodestyle tests/
    - pipenv run python -m unittest discover tests/
